export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_ERROR = "GET_CONTACT_ERROR";
export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST";

export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";
