
export const POST_COMPANY_REQUEST="POST_COMPANY_REQUEST";
export const POST_COMPANY_SUCESS="POST_COMPANY_SUCESS";
export const POST_COMPANY_FAILURE="POST_COMPANY_FAILURE";

export const GET_COMPANY_REQUEST="GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCESS="GET_COMPANY_SUCESS";
export const GET_COMPANY_FAILURE="GET_COMPANY_FAILURE";